/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frame.java
 *
 * Created on 31-Jan-2014, 09:46:58
 */
package log;
import java.util.ArrayList;
import java.util.List;
import org.jfree.ui.RefineryUtilities;
/**
 *
 * @author striker
 */
public class Frame extends javax.swing.JFrame {

    /** Creates new form Frame */
    public Frame() {
        initComponents();
        int parameter = 24;
          List<String> finalresult = new ArrayList<String>();
        finalresult.add("2014-01-06T00#323.90988");
 finalresult.add("2014-01-06T01#229.06938");
 finalresult.add("2014-01-06T02#740.6015");
 finalresult.add("2014-01-06T03#8383.697");
 finalresult.add("2014-01-06T04#8998.523");
 finalresult.add("2014-01-06T05#4822.339");
 finalresult.add("2014-01-06T06#3153.6895");
 finalresult.add("2014-01-06T07#0");
 finalresult.add("2014-01-06T08#0");
 finalresult.add("2014-01-06T09#708.0818");
 finalresult.add("2014-01-06T10#984.643");
 finalresult.add("2014-01-06T11#1032.6699");
 finalresult.add("2014-01-06T12#0");
 finalresult.add("2014-01-06T13#0.002754");
 finalresult.add("2014-01-06T14#0.008262");
 finalresult.add("2014-01-06T15#0.011318");
 finalresult.add("2014-01-06T16#0");
 finalresult.add("2014-01-06T17#3.886679");
 finalresult.add("2014-01-06T18#3.883925");
 finalresult.add("2014-01-06T19#0");
 finalresult.add("2014-01-06T20#0.021995");
 finalresult.add("2014-01-06T21#931.83215");
 finalresult.add("2014-01-06T22#54.01544");  
 finalresult.add("2014-01-06T23#376.354");
        
        
         String T[] = new String[parameter];
 String S[] = {finalresult.get(0).substring(0, 10)};
 double data[][] = new double[1][parameter];
 double amount[] = new double[parameter];
 double amount2[] = new double[parameter];
 
 
 for(int i=0;i<parameter;i++){
   
     T[i] = finalresult.get(i).substring(10, 13);
     amount[i] = Double.parseDouble(finalresult.get(i).substring(14));
     //amount[i] = Double.parseDouble(finalresult2.get(i).substring(14));
     data[0][i] = amount[i];

 }
        
        final Grafico chart = new Grafico("Vertical Bar Chart", T, S, data);
          chart.pack();
  
        RefineryUtilities.centerFrameOnScreen(chart);
         
     jPanel1.add(chart.getContentPane());
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 540));

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jButton1)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
       
         
         
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                
                new Frame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
